apiVersion: v1
kind: PersistentVolume
metadata:
  name: zitadel-hostpath-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8s/pv/nutrix/zitadel-db    # Replace with the actual path on the host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zitadel-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zitadel-db
spec:
  serviceName: "zitadel-db"
  replicas: 1
  selector:
    matchLabels:
      app: zitadel-db
  template:
    metadata:
      labels:
        app: zitadel-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"  # Replace with a strong password
        - name: POSTGRES_DB
          value: "postgres"
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: zitadel-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zitadel-db
spec:
  ports:
  - port: 5432
  selector:
    app: zitadel-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel
spec:
  selector:
    matchLabels:
      app: zitadel
  replicas: 1
  template:
    metadata:
      labels:
        app: zitadel
    spec:
      containers:
      - name: zitadel
        image: ghcr.io/zitadel/zitadel:latest
        args:
        - start-from-init
        - --masterkey
        - MasterkeyNeedsToHave32Characters
        - --tlsMode
        - disabled
        env:
        - name: ZITADEL_DATABASE_POSTGRES_HOST
          value: zitadel-db
        - name: ZITADEL_DATABASE_POSTGRES_PORT
          value: {{ .Values.zitadel.database.postgres.port | quote }}
        - name: ZITADEL_DATABASE_POSTGRES_DATABASE
          value: {{ .Values.zitadel.database.postgres.database }}
        - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
          value: {{ .Values.zitadel.database.postgres.user.username }}
        - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
          value: {{ .Values.zitadel.database.postgres.user.password }}
        - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
          value: {{ .Values.zitadel.database.postgres.user.sslMode }}
        - name : ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
          value: {{ .Values.zitadel.database.postgres.admin.username }}
        - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
          value: {{ .Values.zitadel.database.postgres.admin.password }}
        - name: ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
          value: {{ .Values.zitadel.database.postgres.admin.sslMode }}
        - name: ZITADEL_EXTERNALSECURE
          value: {{ .Values.zitadel.externalSecure | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: zitadel-nodeport
spec:
  type: NodePort
  selector:
    app: zitadel
  ports:
    - port: 2020
      targetPort: 2020
      nodePort: 32020

