deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    allow_admin:
      - 0.0.0.0/0  # Please set it to the subnet address you obtained.
                  # If not set, by default all IP access is allowed.
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

plugins:                         # Enabled plugins
  - cors                         # CORS support
  - proxy-rewrite
  - limit-req
  - prometheus
  - key-auth
  - jwt-auth
  - zipkin
  - http-logger
  - node-status


plugin_attr:
  cors:
    allow_origins: "*"           # Default: Allow all origins (customize as needed)
    allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
    allow_headers: "*"
    expose_headers: "*"
    max_age: 5
    allow_credential: false
