---
etcd:
  prefix: /apisix
  timeout: 30
  watch_timeout: 50
  startup_retry: 2
  host:
  - http://etcd:2379
  tls:
    verify: true
apisix:
  enable_control: true
  disable_sync_configuration_during_start: false
  node_listen:
  - 9080
  proxy_mode: http
  enable_reuseport: true
  normalize_uri_like_servlet: false
  extra_lua_path: ''
  delete_uri_tail_slash: false
  enable_resolv_search_opt: true
  events:
    module: lua-resty-events
  router:
    http: radixtree_host_uri
    ssl: radixtree_sni
  show_upstream_status_in_response_header: false
  data_encryption:
    enable_encrypt_fields: true
    keyring:
    - qeddd145sfvddff3
    - edd1c9f0985e76a2
  resolver_timeout: 5
  ssl:
    enable: true
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl_session_tickets: false
    listen:
    - port: 9443
      enable_http3: false
    ssl_protocols: TLSv1.2 TLSv1.3
    ssl_trusted_certificate: /etc/ssl/certs/ca-certificates.crt
  enable_server_tokens: true
  enable_ipv6: true
  extra_lua_cpath: ''
  enable_dev_mode: false
  enable_http2: true
  proxy_cache:
    cache_ttl: 10s
    zones:
    - memory_size: 50m
      disk_size: 1G
      disk_path: /tmp/disk_cache_one
      cache_levels: '1:2'
      name: disk_cache_one
    - name: memory_cache
      memory_size: 50m
  enable_admin: true
nginx_config:
  main_configuration_snippet: ''
  http_configuration_snippet: ''
  http_server_configuration_snippet: ''
  http_server_location_configuration_snippet: ''
  http_admin_configuration_snippet: ''
  error_log: logs/error.log
  event:
    worker_connections: 10620
  stream:
    enable_access_log: false
    access_log: logs/access_stream.log
    access_log_format: $remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received
      $session_time
    access_log_format_escape: default
    lua_shared_dict:
      lrucache-lock-stream: 10m
      plugin-limit-conn-stream: 10m
      worker-events-stream: 10m
      tars-stream: 1m
      etcd-cluster-health-check-stream: 10m
  worker_processes: auto
  enable_cpu_affinity: false
  worker_rlimit_nofile: 20480
  worker_shutdown_timeout: 240s
  max_pending_timers: 16384
  max_running_timers: 4096
  meta:
    lua_shared_dict:
      prometheus-metrics: 15m
  http:
    variables_hash_max_size: 2048
    access_log_buffer: 16384
    lua_shared_dict:
      balancer-ewma-locks: 10m
      plugin-limit-count: 10m
      plugin-limit-conn: 10m
      plugin-limit-count-redis-cluster-slot-lock: 1m
      plugin-limit-conn-redis-cluster-slot-lock: 1m
      plugin-limit-req-redis-cluster-slot-lock: 1m
      plugin-limit-req: 10m
      prometheus-metrics: 10m
      discovery: 1m
      jwks: 1m
      introspection: 10m
      ocsp-stapling: 10m
      cas-auth: 10m
      tars: 1m
      ext-plugin: 1m
      access-tokens: 1m
      etcd-cluster-health-check: 10m
      plugin-api-breaker: 10m
      tracing_buffer: 10m
      plugin-ai-rate-limiting-reset-header: 10m
      plugin-ai-rate-limiting: 10m
      balancer-ewma-last-touched-at: 10m
      internal-status: 10m
      upstream-healthcheck: 10m
      worker-events: 10m
      lrucache-lock: 10m
      balancer-ewma: 10m
    keepalive_timeout: 60s
    charset: utf-8
    client_header_timeout: 60s
    client_body_timeout: 60s
    client_max_body_size: 0
    send_timeout: 10s
    underscores_in_headers: 'on'
    real_ip_header: X-Real-IP
    upstream:
      keepalive: 320
      keepalive_requests: 1000
      keepalive_timeout: 60s
    enable_access_log: true
    access_log: logs/access.log
    access_log_format: $remote_addr - $remote_user [$time_local] $http_host "$request"
      $status $body_bytes_sent $request_time "$http_referer" "$http_user_agent" $upstream_addr
      $upstream_status $upstream_response_time "$upstream_scheme://$upstream_host$upstream_uri"
    proxy_ssl_server_name: true
    real_ip_recursive: 'off'
    access_log_format_escape: default
    real_ip_from:
    - 127.0.0.1
    - 'unix:'
  stream_configuration_snippet: ''
  http_end_configuration_snippet: ''
  error_log_level: debug
plugin_attr:
  server-info:
    report_ttl: 60
  opentelemetry:
    collector:
      request_headers:
        Authorization: token
      address: 127.0.0.1:4318
      request_timeout: 3
    resource:
      service.name: APISIX
    trace_id_source: x-request-id
    set_ngx_var: false
    batch_span_processor:
      drop_on_queue_full: false
      max_queue_size: 1024
      batch_timeout: 2
      inactive_timeout: 1
      max_export_batch_size: 16
  dubbo-proxy:
    upstream_multiplex_count: 32
  cors:
    max_age: 5
    allow_methods: GET,POST,PUT,DELETE,OPTIONS
    allow_credential: false
    allow_headers: '*'
    expose_headers: '*'
    allow_origins: '*'
  log-rotate:
    timeout: 10000
    interval: 3600
    max_kept: 168
    max_size: -1
    enable_compression: false
  proxy-mirror:
    timeout:
      send: 60s
      connect: 60s
      read: 60s
  prometheus:
    export_uri: /apisix/prometheus/metrics
    enable_export_server: true
    export_addr:
      port: 9091
      ip: 127.0.0.1
    metric_prefix: apisix_
  zipkin:
    set_ngx_var: false
  skywalking:
    report_interval: 3
    endpoint_addr: http://127.0.0.1:12800
    service_name: APISIX
    service_instance_name: APISIX Instance Name
  inspect:
    delay: 3
    hooks_file: /usr/local/apisix/plugin_inspect_hooks.lua
graphql:
  max_size: 1048576
stream_plugins:
- ip-restriction
- limit-conn
- mqtt-proxy
- syslog
deployment:
  config_provider: etcd
  etcd:
    prefix: /apisix
    timeout: 30
    watch_timeout: 50
    startup_retry: 2
    host:
    - http://etcd:2379
    tls:
      verify: true
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    enable_admin_cors: true
    admin_key:
    - role: admin
      name: admin
      key: pSZfIaNudNMlkMzttzvYwXXrKvMYXdbk
    admin_listen:
      port: 9180
      ip: 0.0.0.0
    admin_key_required: true
    allow_admin:
    - 0.0.0.0/0
    admin_api_version: v3
plugins:
- cors
- proxy-rewrite
- limit-req
- prometheus
- key-auth
- jwt-auth
- zipkin
- http-logger
- node-status
- openid-connect
- serverless-pre-function
- serverless-post-function
...
